before_install:
 - chmod +x NobankCore/gradlew
 
language: android
jdk: oraclejdk8

android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
  
before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
  
script: NobankCore/gradlew -b "NobankCore/build.gradle" clean testDebugUnitTest jacocoTestReport assembleDebug -Pproguard -PtestCoverage

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/