language: android
jdk: oraclejdk7

android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  - build-tools-22.0.1
  - android-22
  - extra-google-m2repository
  - extra-android-m2repository
  
script: gradle -b "NobankCore/build.gradle" clean :noBank:testDebugUnitTest assembleDebug -Pproguard